# Generated by Django 3.0.5 on 2020-05-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='RecipeItems',
        ),
    ]
